CREATE DATABASE IF NOT EXISTS TaxeFacile;
Use TaxeFacile;

CREATE TABLE IF NOT EXISTS ICMS (
	idICMS INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	stateOrigin VARCHAR(18) NOT NULL,
	aliquot DOUBLE NOT NULL,
	stateDestiny VARCHAR(18) NOT NULL
);